# This file strictly follows the rules defined in the Ruby style guide:
#   http://shopify.github.io/ruby-style-guide/
inherit_gem:
  rubocop-shopify: rubocop.yml

require:
  - rubocop/cop/internal_affairs

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - vendor/**/*

InternalAffairs:
  Enabled: false

InternalAffairs/InheritDeprecatedCopClass:
  Enabled: true

Naming/FileName:
  Exclude:
  - lib/rubocop-sorbet.rb
