#
# Configuration for obsoletion.
#
# See: https://docs.rubocop.org/rubocop/extensions.html#config-obsoletions
#
removed:
  Sorbet/OneAncestorPerLine:
    reason: '`require_ancestor` now takes a block instead of arguments'

changed_parameters:
  - cops: 'Sorbet/EnforceSignatures'
    parameters: 'AllowRBS'
    alternative: 'Style'
